version: '3'

services:

  elasticsearch:
    image: elasticsearch:2.4.6-alpine
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data/master:/usr/share/elasticsearch/data
    networks:
      - elk

  elasticsearch_slave:
    image: elasticsearch:2.4.6-alpine
    networks:
      - elk
    volumes:
      - ./data/slave:/usr/share/elasticsearch/data
    depends_on:
      - elasticsearch
    command: elasticsearch --discovery.zen.ping.unicast.hosts=elasticsearch

networks:
  elk:
    driver: bridge
